### ISSUE TITLE
Prod size is too large

### ISSUE THREAD

**Issue by larionov** [Gonzih/glue-demo#1]
After building 'min' target I'm getting `glue_demo.js` 290Kb in size. Is that supposed to be like that?

**Comment by Gonzih** [comment]
This resulting js bundles vue js code, parts of clojure.core and demo logic. Demo logic being the smallest part. So I would say yeah, sounds like this would be an outcome of those things combined.

**Comment by Gonzih** [comment]
Closing the issue, feel free to re-open if you have any other questions.
